### ISSUE TITLE
Makefile in data - No need to unzip all the files

### ISSUE THREAD

**Issue by soazig** [berkeley-stat159/project-epsilon#125]
Hello @mingujo 

As I said, we don't need to unzip all the files when we download them.
We definitely don't need to unzip the BOLD data. 
I think we should remove the "unzip" part of the Makefile and see if the Travis can pass the test.

**Comment by mingujo** [comment]
@soazig 

I got it. should I make another branch to do this?

**Comment by soazig** [comment]
Yes, maybe. 
@mingujo , you can merge it to the travis branch I created.
I tried on my own and the Travis is not passing the test for data,py.
I tried to check the team alpha, it seems like we need to specify the location of our tests somewhere but I can't figure this out.

**Comment by soazig** [comment]
I did it, see the branch called data.
Still working on the tests functions.
