### ISSUE TITLE
How do we create a test for the download of the filtered data ?

### ISSUE THREAD

**Issue by soazig** [berkeley-stat159/project-epsilon#140]
Hello @jarrodmillman @matthew-brett @rossbar 

I created a python script that generates a bash script to be used in the Makefile to be able to download the filtered data and located them in the relevant directories.
I understand how we used this checksum txt (http://openfmri.s3.amazonaws.com/tarballs/ds005_raw_checksums.txt)
to test our data from open fMRI as we check the hashes.
How do I do the test without hashes ? Do I need to generate them ?

This will be helpful to create a test for the filtered data that we download. We also want to use the data from ds114 provided in class to test some functions. I could not find the relative hashes for that. 

Thank you for your answers.
Soazig
@mingujo

**Comment by matthew-brett** [comment]
Yes, that's right - if you don't have the hashes, you'll have to calculate them and store them in the repo.

Obviously that doesn't protect you against images that got damaged as they were downloaded to your machine, but it does mean that you can check whether everyone in the group has the same data.  For example, if there was a problem with your download, then, when you commit your hashes, and someone else checks the hashes, they should get a mismatch, unless they had the same download error.

**Comment by soazig** [comment]
I did, thank you !
