### ISSUE TITLE
Required version of the package future ?

### ISSUE THREAD

**Issue by soazig** [berkeley-stat159/project-epsilon#151]
Hello @matthew-brett @jarrodmillman 

So far, some of our build/coverage problem come from the compatibility between Python 2 and 3.
I was wondering if you recommend installing the package 'future'. In that case, I don't know which version I should put in the requirements ?
Now I am running version 0.15.2
Thank you,
Soazig

**Comment by matthew-brett** [comment]
I haven't personally used `future` - I have only used the `six` package - if you do want to use it, please go ahead.

Feel free to point us to Python 2 / Python 3 build problems with issues - it's usually quick for us to solve them, and we'd rather you concentrate on the science stuff than the Python compatibility stuff.

**Comment by soazig** [comment]
Thank you !
