### ISSUE TITLE
Can someone put 2 of the new images in the data file so I can work on it ?

### ISSUE THREAD

**Issue by soazig** [berkeley-stat159/project-epsilon#165]
Hello guys,

When I download the data one by one, I cannot use them for analysis.
Can someone add 2 images from the new data on the data folder so that I can tests my code ?
(my download of the .tar folder still need 5 hours)

Thanks
@mingujo @ye-zhi @timothy1191xa @lizhua

**Comment by timothy1191xa** [comment]
@soazig 

Do you want me to upload 2 of the 16 subjects then?

**Comment by soazig** [comment]
Hello @timothy1191xa 
Yes but from the new data from this website : https://nipy.bic.berkeley.edu/rcsds/
if you have them already of course.
I think @mingujo has some data already.
