### ISSUE TITLE
Working on new data - same hashes when downloaded one by one or .tar

### ISSUE THREAD

**Issue by soazig** [berkeley-stat159/project-epsilon#197]
Hello @mingujo , @ye-zhi 

You told me you managed to work with the new data. As I said yesterday, when I do data = img.get_data() I got an error.
Can you put the link of the scripts you did that ?
I must do something wrong.

Also, I checked the hashes of the files you sent me. They are the same as the files I can download one by one. So I will keep the download data one by one since thus takes only 10s/data.
I was thinking I could just unzip them in the same ds005 directory as the original data. what do you think ?

Thanks!

**Comment by soazig** [comment]
Actually,

I think I have a lead on the data thing.
thanks

**Comment by mingujo** [comment]
https://github.com/berkeley-stat159/project-epsilon/blob/multi/code/utils/scripts/multi_beta_script.py

So in this script, you'll see how i'm using it in the middle.
For me, I downloaded the whole filtered data set under the data folder, unzipped, and named as "ds005_2"

I'm not sure downloading one by one would work.
As long as the hashes are same, they would work. 
Approximately, one data is large as ~250MB
Downloading that large file in 10sec must be either your internet is super fast or something is wrong...

@soazig

**Comment by soazig** [comment]
Great, 

I changed the server where I run my code and it is working now.
Also working on the downloaded data one by one, as I said, they have the same hashes so I think it is safe. We can discuss later.
Thank you !
