### ISSUE TITLE
Bibliography reference rename

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-epsilon#20]
In your project.bib in the `paper/` dir, you seem to have updated the citation information without changing the citation label (i.e. it still is under the tag lindquist2008statistical).

This would get very confusing in the actual paper as that tag (lindquist...) is how you refer to the reference in the report.tex. Therefore, the tag should match the actual paper you are referencing:

A standard (though not necessary) format for BibTex citation references is <author><year><first word of title>

**Comment by soazig** [comment]
Hello Ross, 

Thank you for the feedback. I actually created to a pull request to change this in our repo last week but changed my mind afterwards. I wanted to fix some issues in our project repo before that - for example, we currently have 3 branches including the master that we still need to merge.
