### ISSUE TITLE
Function for plots

### ISSUE THREAD

**Issue by timothy1191xa** [berkeley-stat159/project-epsilon#229]
Hello, @jarrodmillman @rossbar @matthew-brett 

We have a function that can generate the plot. However, we don't really know how to write a test for this function, and it will just lower the coverage in Travis CI (we usually put codes involving plots in scripts so the coverage wouldn't be affected). I was wondering if we should just rewrite the code to generate such plot. 

Thanks!

**Comment by matthew-brett** [comment]
Don't worry too much about the absolute value for the coverage.  It's hard to do tests for the plots.  We'll look at what code you haven't covered, and take into account if it was hard to cover.
