### ISSUE TITLE
GLM and T-test

### ISSUE THREAD

**Issue by soazig** [berkeley-stat159/project-epsilon#329]
@lizhua @ye-zhi @mingujo 

So the glm and t_test script were only set for subject 1, 5, 11.
Don't we need all the betas for the multi comparison ?

The t_test_plot script has a lot of unneeded lines + looping through subject 1,5,11. don't you only use the subject 1 for he report ?

**Comment by timothy1191xa** [comment]
btw i think the girls can't access gmail in China.

## 

_Timothy Yu_
University of California, Berkeley | Class of 2016
B.A. Statistics
(408) 805-2371 | timothy1191xa@berkeley.edu

**Comment by soazig** [comment]
Never mind, we have all betas in muli_betas script sorry

**Comment by soazig** [comment]
Sorry I closed the issue,
