### ISSUE TITLE
General question : Is it better to display the images while running the analysis ?

### ISSUE THREAD

**Issue by soazig** [berkeley-stat159/project-epsilon#342]
Hello @rossbar , @matthew-brett , @jarrodmillman 

I was wondering if there is a best practice for dealing with figures, plots and results.
We are rendering lost of plots and text files but we only use a few of them in the report.
I was wondering if this would be better to display the pictures that are in the report while the analysis is run ?

Thank you !

**Comment by rossbar** [comment]
What I often do is include optional flags for any analysis I'm running. By default, I won't print any images (you never know if the user actually has a graphics display) or print out anything big to the screen. You can then provide options like `-i --make-images` or `-v --verbose` that toggle whether or not you display these types of things while the analysis is being run.

This is just my two cents, In general I think it's application dependent.

**Comment by soazig** [comment]
Thank you @rossbar !
