### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jarrodmillman** [berkeley-stat159/project-epsilon#44]
Good, clear description of the loss-aversion paper.

Great work with the initial regressor analysis; I liked to see the results of
the preliminary regressor applied to the data - represents real, tangible
progress toward an ultimate goal.

Clear presentation of the goal to experiment with the HRF model - was less clear
about where the motivation to do so came from; might want to justify the
decision to investigate this aspect a bit more.  For example, there is a published
literature addressing this question to some extent.  You don't need to replicate
the state of the art here, but you should reference existing work as part of
your motivation.

Seemed to have a very solid understanding of what they knew about the data, and
what they still needed to understand (PTvals for instance). Also have clearly
done literature review outside of their paper to help with the coding aspect
(PEP8).

The group seems clearly capable and invested in the project, just might want to
focus on specific tasks a bit more.

You should make sure your code is valid.  For instance,

```
$ python eda_behav.py
  File "eda_behav.py", line 3
    %matplotlib
    ^
SyntaxError: invalid syntax
```

You still have a lot of work to do, but there is still time.

**Comment by jarrodmillman** [comment]
I am starting to get concerned about your progress.  It looks like not much was accomplished this week and I am not sure how much time you will have next week.  If you are having trouble getting started, please let us know.

I am already pretty booked meeting with other teams this week, so unfortunately I don't have many available slots left.  But I may have time on Tuesday or Wednesday late afternoon.  Please let me know if you would like to meet to go over questions or get more feedback.

Time is running short and you still have a lot of work to do. If you have run into a major problem, please let me know immediately.

Please review the grading criteria:
http://www.jarrodmillman.com/rcsds/notes/rubric.pdf

As well as my comments from lecture 22:
http://www.jarrodmillman.com/rcsds/lectures/day22.html

**Comment by lizhua** [comment]
Hi @jarrodmillman Jarrod,

So we want to schedule a meeting with you. Can you tell us what exact time you mean by late afternoon? We are available on Tuesday or wednesday afternoon

**Comment by jarrodmillman** [comment]
Let's meet on Tuesday (11/24) at 17:00 in 210Q Barker
