### ISSUE TITLE
Question regarding the linear regression on a voxel

### ISSUE THREAD

**Issue by ye-zhi** [berkeley-stat159/project-epsilon#54]
We generated new convolution data into txt files using the method "Using onsets that do not start on a TR" provided on Day 25. We tried to use them as beta predictors but since it has too many rows (2400) (dividing TR into 10 intervals), it does not fit with our image data (240 time steps). 

How should we decrease the number of convolution data so we can do the linear regression on a voxel of an image data?
If we cannot decrease, is there any method for this issue?
@jarrodmillman

**Comment by soazig** [comment]
@ye-zhi 

Hello Ze, Matthew covered this in class at the end of the lecture - take a look here at the  tr_hemo defined here http://www.jarrodmillman.com/rcsds/lectures/non_tr_onsets.html
tr_hemo = high_res_hemo[hr_tr_indices]
There are shown as the 'x' markers in the last figure.
I will be working on this later this afternoon as well.
